FROM java
VOLUME /tmp
ADD ./build/libs/miscroservice*.jar /miscroservice.jar
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
ENV  innerAddress=""
ENTRYPOINT [ "sh", "-c", "java -Djava.security.egd=file:/dev/./urandom -Dspring.profiles.active=center -Deureka.instance.ip-address=$innerAddress -Dlog.path=/stock/logs/ -Xms126m -Xmx256m -jar /miscroservice.jar" ]
