---
#限流开关
limter.flow.enabled: false
---
#文件加载的环境配置
spring:
  profiles:
    active: test
  application:
    name: supplier

---
#端口
server:
  port: 8062

#开启熔断机制
feign.hystrix.enabled: true

#支付宝支付
#aliKeyNew: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCnxj/9qwVfgoUh/y2W89L6BkRAFljhNhgPdyPuBV64bfQNN1PjbCzkIM6qRdKBoLPXmKKMiFYnkd6rAoprih3/PrQEB/VsW8OoM8fxn67UDYuyBTqA23MML9q1+ilIZwBC2AQ2UBVOrFXfFl75p6/B5KsiNG9zpgmLCUYuLkxpLQIDAQAB
#privateKeyNew: MIICeAIBADANBgkqhkiG9w0BAQEFAASCAmIwggJeAgEAAoGBAMZYBIwKoen8lwRI+WJtyubqBbeqCHTkcS0/swrEjd0oIVEd2uFNQ0JDgpTnfyTtoJs7GJFOgmFohK2xxepOTDe3fbwAOC8NUWTswWgU3x9WitokuIa8Z4et2UqoXxYDNA1En8Oy0UjE4rvoP8d0T6zRdL5SG5BjREaLDAaa0pWZAgMBAAECgYEAm4wDZOAhwqK4vD+OdEauTRFSkoriPum4aEgAXX1v0/TYzAih0vcIvDq9eZFjAM7qmVJrHel4DnQtORqln+7vjY97aDTFhr0QGc84RzelGtAgG+ra0s9uNtm3lOwPDZ2khRIDW8m3FxP03gmtKiGvLynmpIhn8miwfORs7ic0cAECQQD3Yo2zKib3CCVJfLfJ4GDWTsWlAjAh0K1tNOVQMgjjmUZg2pC2u23c/+FvxkmQQ0r19TkR/CY6Qe8FczRwkPMZAkEAzUBCrpzY6iktT7KitJG/xRiyAElOrtOg5HZ/lfWnqxmT87oh7LW4GpKH6fbQHyzp2fR7CMrI2sEVc0IPaPGGgQJALKe3mF3FhtYLlQZUTraYBFdXyf9pHNGEXLAtrJo7jIoAcD9D3BhdLoVp9jk+0jGzeE55rMttQxrfwIYZMzCXEQJBAMkJ6Eaf2teA/aDSmAvFttCXH8KoCymyoCUm7FE2DMTKiOBxsEjqtSlR3U6NMc1XcLbLgLdb6OBbv2bljbJ84AECQQCk+kmViCyjD72IFBYb2+8a1Yhnc8q2q/HukEHikVJrtnZvB6wBlD8nqqcennsMpugfRkmnTYFFVQopKjoMT1Kp

#远程调用退款
url: http://192.168.1.188:8083/shop/refundOrder/refund/newRefundMoney/auth.json
---
#mybatis的扫包路径
mybatis:
  typeAliasesPackage: com.e_commerce.miscroservice.supplier.po
  mapper-locations: classpath:mapper/*.xml

mapper:
  identity: MYSQL
  mappers:
  - com.e_commerce.miscroservice.commons.helper.plug.mybatis.mapper.BaseMapper
  not-empty: false

pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true

---
#打开数据库配置
open.datasource: true
flyway.enabled: false


---
#mq管理
mq:
  #是否打开发送开关 true是 false不是
  openSend: false
  # 发送消息的集合管理  格式  消息名称:消息的类型(fanout,direct):接受的监听类的名称(首字母小写) eg msg:fanout:demoListener
  channels: timer_scheduler_timer_send_withdraw_deposit_bank_delay_task:fanout:withdrawDepositListener
