/**
 * onway.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.baib.common.dal.ibatis;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.onway.baib.common.dal.daointerface.SysConfigDAO;

import com.onway.baib.common.dal.dataobject.SysConfigDO;
import java.util.List;
import org.springframework.dao.DataAccessException;
import java.util.Map;
import java.util.HashMap;

/**
 * An ibatis based implementation of dao interface <tt>com.onway.baib.common.dal.daointerface.SysConfigDAO</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/baib_sys_config.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: IbatisSysConfigDAO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public class IbatisSysConfigDAO extends SqlMapClientDaoSupport implements SysConfigDAO {
	/**
	 *  Query DB table <tt>baib_sys_config</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, sys_key, sys_value, status, memo, gmt_create, gmt_modified from baib_sys_config</tt>
	 *
	 *	@return List<SysConfigDO>
	 *	@throws DataAccessException
	 */	 
    public List<SysConfigDO> loadAll() throws DataAccessException {


        return getSqlMapClientTemplate().queryForList("MS-SYS-CONFIG-LOAD-ALL", null);

    }

}