/**
 * onway.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.baib.common.dal.ibatis;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.onway.baib.common.dal.daointerface.RoleDAO;

import com.onway.baib.common.dal.dataobject.RoleDO;
import org.springframework.dao.DataAccessException;
import java.util.Map;
import java.util.HashMap;

/**
 * An ibatis based implementation of dao interface <tt>com.onway.baib.common.dal.daointerface.RoleDAO</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/baib_role.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: IbatisRoleDAO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public class IbatisRoleDAO extends SqlMapClientDaoSupport implements RoleDAO {
	/**
	 *  Query DB table <tt>baib_role</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select ID, USER_ID, USER_NAME, PASSWORD, ROLE, CREATER, GMT_CREATE, MODIFIER, GMT_MODIFIED, MEMO from baib_role where (ID = ?)</tt>
	 *
	 *	@param id
	 *	@return RoleDO
	 *	@throws DataAccessException
	 */	 
    public RoleDO selectRoleInfoById(int id) throws DataAccessException {

        Integer param = new Integer(id);

        return (RoleDO) getSqlMapClientTemplate().queryForObject("MS-ROLE-SELECT-ROLE-INFO-BY-ID", param);

    }

}