server:
  port: 8087
  address: 0.0.0.0
  servlet:
    context-path: /
spring:
    thymeleaf:
        enabled: true
        cache: false
        prefix: classpath:/templates/
        suffix: .html
    datasource:
        driver-class-name:  com.mysql.jdbc.Driver
        url: jdbc:mysql://rm-uf6w182s6385yl3phgo.mysql.rds.aliyuncs.com:3306/yjjlocal?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
        username: mysql
        password: daf24fzirewafarqgwba131
        initialSize: 10
        minIdle: 10
        maxActive: 300
        maxWait: 200
        validationQuery: select 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        filters: stat,wall,log4j2
        logSlowSql: true
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8


mybatis:
  mapperLocations: classpath*:com/jiuy/**/xml/*.xml
  config-location: classpath:mybatis-config-jdbc.xml

logging:
  config: classpath:log4j2.xml
