/**
 * onway.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.baib.common.dal.daointerface;


/**
 * A dao interface provides methods to access all <tt>SEQUENCE</tt> objects.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file. 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: SeqDAO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public interface SeqDAO {
}