---
#限流开关
limter.flow.enabled: false
---
#文件加载的环境配置
spring:
  profiles:
    active: test
  application:
    name: crm

---
#端口
server:
  port: 8071

#开启熔断机制
feign.hystrix.enabled: true

---
#mybatis的扫包路径
#mybatis 驼峰转换
mybatis:
  typeAliasesPackage: com.e_commerce.miscroservice.crm.po
  configuration:
    mapUnderscoreToCamelCase: true
    map-underscore-to-camel-case: true
  type-aliases-package: tk.mybatis.springboot.model
  mapper-locations: classpath:crmMapper/*.xml
---
########## 分页插件 ##########
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
---
#打开数据库配置
open.datasource: true
flyway.enabled: false

---
#mq管理
mq:
  #是否打开发送开关 true是 false不是
  openSend: false
  # 发送消息的集合管理  格式  消息名称:消息的类型(fanout,direct):接受的监听类的名称(首字母小写) eg msg:fanout:demoListener
  channels: timer_scheduler_timer_send_withdraw_deposit_bank_delay_task:fanout:withdrawDepositListener
