FROM java
VOLUME /tmp
ADD ./build/libs/miscroservice*.jar /miscroservice.jar
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom","-Dspring.profiles.active=dev","-Deureka.instance.ip-address=47.96.167.92","-Dlog.path=/stock/logs/","-Deureka.instance.registerInfo=47.96.167.92","-Xms512m","-Xmx1024m","-jar","/miscroservice.jar"]
