FROM java
VOLUME /tmp
ADD ./build/libs/miscroservice*.jar /miscroservice.jar
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom","-Dlog.path=/stock/logs/","-Deureka.instance.registerInfo=47.96.167.92","-Dspring.cloud.client.ipAddress=47.96.167.92","-Xms20m","-Xmx126m","-jar","/miscroservice.jar"]
