FROM java
VOLUME /tmp
ADD ./build/libs/miscroservice*.jar /miscroservice.jar
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom","-Deureka.instance.registerInfo=101.37.151.54","-Dlog.path=/stock/logs/","-Xms20m","-Xmx126m","-jar","/miscroservice.jar"]
