package com.e_commerce.miscroservice.store.entity.vo;
import com.e_commerce.miscroservice.commons.annotation.colligate.table.Table;
import com.e_commerce.miscroservice.commons.annotation.colligate.table.Id;
import lombok.Data;
 @Data
 @Table("yjj_product")
 public class Product {
@Id
private Long id;
private String name;
private Long categoryid;
private String detailimages;
private String summaryimages;
private Integer status;
private Long salestarttime;
private Long saleendtime;
private Integer salecurrencytype;
private Integer saletotalcount;
private Integer salemonthlymaxcount;
private Integer price;
private Long favorite;
private Long assessmentcount;
private Integer expressfree;
private String expressdetails;
private Long createtime;
private Long updatetime;
private String productseq;
private String sizetableimage;
private String clothesnumber;
private String promotionimage;
private Integer weight;
private Integer showstatus;
private Integer marketpricemin;
private Integer marketpricemax;
private Integer type;
private Integer jiucoin;
private Integer restricthistorybuy;
private Integer restrictdaybuy;
private Integer promotionsetting;
private Integer promotionjiucoin;
private Long promotionstarttime;
private Long promotionendtime;
private Integer restrictcycle;
private Long restricthistorybuytime;
private Long restrictdaybuytime;
private Long lowarehouseid;
private Long restrictid;
private Long vcategoryid;
private String together;
private Long subscriptid;
private Integer buytype;
private Integer displaytype;
private Integer promotionbuytype;
private Integer promotiondisplaytype;
private Integer promotionsalecount;
private Integer promotionvisitcount;
private Long lowarehouseid2;
private Integer setlowarehouseid2;
private String videourl;
private String videoname;
private Integer vip;
private Long videofileid;
private Integer state;
private Integer delstate;
private Long submitaudittime;
private Long audittime;
private String auditnopassreason;
private Long upsoldtime;
private Long downsoldtime;
private Long newtime;
private Integer skucount;
private String mainimg;
private Long onecategoryid;
private String onecategoryname;
private Long twocategoryid;
private String twocategoryname;
private Long threecategoryid;
private String threecategoryname;
private String brandname;
private String brandlogo;
private Integer needaudit;
private String ladderpricejson;
private Long supplierid;
private String categoryids;
private Long badgeId;
private String badgeName;
private String badgeImage;
private Integer rank;
private Integer brandType;
private Long lastPutonTime;
private String vedioMain;
private String memberLadderPriceJson;
private Integer memberlevel;
}