package com.e_commerce.miscroservice.store.entity.vo;
import com.e_commerce.miscroservice.commons.annotation.colligate.table.Table;
import com.e_commerce.miscroservice.commons.annotation.colligate.table.Id;
import java.math.BigDecimal;
import lombok.Data;
 @Data
 @Table("store_order")
 public class StoreOrder {
@Id
private Long orderno;
private String ordernoAttachmentStr;
private Long storeid;
private Integer ordertype;
private Integer orderstatus;
private BigDecimal totalmoney;
private BigDecimal totalpay;
private BigDecimal platformTotalPreferential;
private BigDecimal supplierTotalPreferential;
private BigDecimal supplierPreferential;
private BigDecimal supplierChangePrice;
private BigDecimal originalPrice;
private BigDecimal totalexpressmoney;
private String expressinfo;
private Integer coinused;
private String remark;
private String platform;
private String platformversion;
private String ip;
private String paymentno;
private Integer paymenttype;
private Long parentid;
private Long mergedid;
private Long lowarehouseid;
private Integer status;
private Long createtime;
private Long updatetime;
private BigDecimal totalmarketprice;
private String cancelreason;
private Long pushtime;
private Long expiredtime;
private Long paytime;
private Long sendtime;
private BigDecimal commission;
private BigDecimal availablecommission;
private BigDecimal commissionpercent;
private Long brandorder;
private Integer totalbuycount;
private Integer haswithdrawed;
private Long supplierid;
private Long grounduserid;
private String superids;
private Integer confirmsigneddate;
private Long confirmsignedtime;
private Integer orderCloseType;
private BigDecimal totalRefundCost;
private BigDecimal totalValidPay;
private Integer refundUnderway;
private Long refundStartTime;
private String expressName;
private String expressPhone;
private String expressAddress;
private Long autoTakeDeliveryPauseTimeLength;
private String orderSupplierRemark;
private Long orderCloseTime;
private Integer hangup;
private Integer lockingOrder;
private Long restrictionActivityProductId;
private Integer classify;
private Integer sendCoupon;
}