package com.e_commerce.miscroservice.store.entity.vo;
import com.e_commerce.miscroservice.commons.annotation.colligate.table.Table;
import com.e_commerce.miscroservice.commons.annotation.colligate.table.Id;
import java.math.BigDecimal;
import lombok.Data;
 @Data
 @Table("supplier_user")
 public class SupplierUser {
@Id
private Integer id;
private String avatar;
private String account;
private String password;
private String salt;
private String name;
private Integer sex;
private String email;
private String phone;
private String roleid;
private Integer deptid;
private Integer status;
private Integer version;
private String alipayName;
private String businessName;
private String companyName;
private String businessAddress;
private String licenseNumber;
private String taxid;
private String legalPerson;
private String idCardNumber;
private String province;
private String city;
private Integer bankCardFlag;
private String bankAccountName;
private String bankName;
private String bankAccountNo;
private Integer alipayFlag;
private String alipayAccount;
private Long lowarehouseId;
private Long brandId;
private Long updatetime;
private Integer storeNumber;
private BigDecimal cashIncome;
private BigDecimal availableBalance;
private String organizationNo;
private String brandLogo;
private String brandShowImgs;
private BigDecimal commissionPercentage;
private Integer settlementDate;
private Integer weixinFlag;
private String weixinAccount;
private String weixinName;
private Integer withdrawSetting;
private BigDecimal expressCashIncome;
private BigDecimal availableExpressCash;
private BigDecimal minWithdrawal;
private BigDecimal bond;
private Long businessNumber;
private String expressBankAccountName;
private String expressBankName;
private String expressBankAccountNo;
private Long addCreatetime;
private Integer isOriginalpassword;
private String receiver;
private String supplierReceiveAddress;
private String receiverPhone;
private String productPermission;
private BigDecimal wholesaleCost;
private Integer wholesaleCount;
private String campaignImage;
}