/**
 * onway.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.baib.common.dal.dataobject;

import org.apache.commons.beanutils.BeanUtils;

import java.io.Serializable;

import java.util.Iterator;
import java.util.Map;

/**
 * Base class for all data objects.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file. 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: BaseDO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public class BaseDO implements Serializable {
    private static final long serialVersionUID = 741231858441822688L;

    /**
     * @return
     *
     * @see java.lang.Object#toString()
     */
    public String toString() {
        try {
            Map          props     = BeanUtils.describe(this);
            Iterator     iProps    = props.keySet().iterator();
            StringBuffer retBuffer = new StringBuffer();

            while (iProps.hasNext()) {
                String key = (String) iProps.next();

                // skip false property "class"
                if ("class".equals(key)) {
                    continue;
                }

                retBuffer.append(key).append("=[").append(props.get(key)).append("]");

                if (iProps.hasNext()) {
                    retBuffer.append(", ");
                }
            }

            return retBuffer.toString();
        } catch (Exception e) {
            return super.toString();
        }
    }
}
