/**
 * onway.com Inc.
 * Copyright (c) 2013-2014 All Rights Reserved.
 */
 package com.onway.baib.common.dal.dataobject;

import com.onway.baib.common.dal.dataobject.BaseDO;

import java.util.Date;

/**
 * A data object class directly models database table <tt>baib_sequence</tt>.
 *
 * This file is generated by <tt>onway-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>onway</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/baib_sequence.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>onway-gen-dal</tt> 
 * to generate this file.
 *
 * @author guangdong.li
 * @version $Id: SequenceDO.java,v 1.0 2013/10/29 07:34:20 guangdong.li Exp $
 */
public class SequenceDO extends BaseDO {
    private static final long serialVersionUID = 741231858441822688L;

    //========== properties ==========

	/**
	 * This property corresponds to db column <tt>BIZ_NAME</tt>.
	 */
	private String bizName;

	/**
	 * This property corresponds to db column <tt>CURRENT_VALUE</tt>.
	 */
	private int currentValue;

	/**
	 * This property corresponds to db column <tt>INCREMENT_VALUE</tt>.
	 */
	private int incrementValue;

	/**
	 * This property corresponds to db column <tt>GMT_CREATE</tt>.
	 */
	private Date gmtCreate;

	/**
	 * This property corresponds to db column <tt>GMT_MODIFIED</tt>.
	 */
	private Date gmtModified;

	/**
	 * This property corresponds to db column <tt>PLATFORM_CODE</tt>.
	 */
	private String platformCode;

    //========== getters and setters ==========

    /**
     * Getter method for property <tt>bizName</tt>.
     *
     * @return property value of bizName
     */
	public String getBizName() {
		return bizName;
	}
	
	/**
	 * Setter method for property <tt>bizName</tt>.
	 * 
	 * @param bizName value to be assigned to property bizName
     */
	public void setBizName(String bizName) {
		this.bizName = bizName;
	}

    /**
     * Getter method for property <tt>currentValue</tt>.
     *
     * @return property value of currentValue
     */
	public int getCurrentValue() {
		return currentValue;
	}
	
	/**
	 * Setter method for property <tt>currentValue</tt>.
	 * 
	 * @param currentValue value to be assigned to property currentValue
     */
	public void setCurrentValue(int currentValue) {
		this.currentValue = currentValue;
	}

    /**
     * Getter method for property <tt>incrementValue</tt>.
     *
     * @return property value of incrementValue
     */
	public int getIncrementValue() {
		return incrementValue;
	}
	
	/**
	 * Setter method for property <tt>incrementValue</tt>.
	 * 
	 * @param incrementValue value to be assigned to property incrementValue
     */
	public void setIncrementValue(int incrementValue) {
		this.incrementValue = incrementValue;
	}

    /**
     * Getter method for property <tt>gmtCreate</tt>.
     *
     * @return property value of gmtCreate
     */
	public Date getGmtCreate() {
		return gmtCreate;
	}
	
	/**
	 * Setter method for property <tt>gmtCreate</tt>.
	 * 
	 * @param gmtCreate value to be assigned to property gmtCreate
     */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

    /**
     * Getter method for property <tt>gmtModified</tt>.
     *
     * @return property value of gmtModified
     */
	public Date getGmtModified() {
		return gmtModified;
	}
	
	/**
	 * Setter method for property <tt>gmtModified</tt>.
	 * 
	 * @param gmtModified value to be assigned to property gmtModified
     */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

    /**
     * Getter method for property <tt>platformCode</tt>.
     *
     * @return property value of platformCode
     */
	public String getPlatformCode() {
		return platformCode;
	}
	
	/**
	 * Setter method for property <tt>platformCode</tt>.
	 * 
	 * @param platformCode value to be assigned to property platformCode
     */
	public void setPlatformCode(String platformCode) {
		this.platformCode = platformCode;
	}
}
