// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: json.prop

package com.finace.miscroservice.rpc.com.test;

public interface SimpleFeatureDatabaseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SimpleFeatureDatabase)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .SimpleFeature feature = 1;</code>
   */
  java.util.List<com.finace.miscroservice.rpc.com.test.SimpleFeature> 
      getFeatureList();
  /**
   * <code>repeated .SimpleFeature feature = 1;</code>
   */
  com.finace.miscroservice.rpc.com.test.SimpleFeature getFeature(int index);
  /**
   * <code>repeated .SimpleFeature feature = 1;</code>
   */
  int getFeatureCount();
  /**
   * <code>repeated .SimpleFeature feature = 1;</code>
   */
  java.util.List<? extends com.finace.miscroservice.rpc.com.test.SimpleFeatureOrBuilder> 
      getFeatureOrBuilderList();
  /**
   * <code>repeated .SimpleFeature feature = 1;</code>
   */
  com.finace.miscroservice.rpc.com.test.SimpleFeatureOrBuilder getFeatureOrBuilder(
      int index);
}
