// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: json.prop

package com.finace.miscroservice.rpc.com.test;

public final class HelloStreamEntity {
  private HelloStreamEntity() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Simple_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Simple_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SimpleList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SimpleList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SimpleFeature_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SimpleFeature_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SimpleSummary_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SimpleSummary_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SimpleFeatureDatabase_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SimpleFeatureDatabase_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tjson.prop\"#\n\006Simple\022\013\n\003num\030\001 \001(\005\022\014\n\004na" +
      "me\030\002 \001(\t\")\n\nSimpleList\022\033\n\nsimpleList\030\001 \003" +
      "(\0132\007.Simple\"8\n\rSimpleFeature\022\014\n\004name\030\001 \001" +
      "(\t\022\031\n\010location\030\002 \001(\0132\007.Simple\"&\n\rSimpleS" +
      "ummary\022\025\n\rfeature_count\030\002 \001(\005\"8\n\025SimpleF" +
      "eatureDatabase\022\037\n\007feature\030\001 \003(\0132\016.Simple" +
      "Feature2\316\001\n\013HelloStream\022&\n\tsimpleRpc\022\007.S" +
      "imple\032\016.SimpleFeature\"\000\0223\n\020server2Client" +
      "Rpc\022\013.SimpleList\032\016.SimpleFeature\"\0000\001\022/\n\020" +
      "client2ServerRpc\022\007.Simple\032\016.SimpleSummar" +
      "y\"\000(\001\0221\n\027bindirectionalStreamRpc\022\007.Simpl" +
      "e\032\007.Simple\"\000(\0010\001B<\n%com.finace.miscroser" +
      "vice.rpc.com.testB\021HelloStreamEntityP\001b\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Simple_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Simple_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Simple_descriptor,
        new java.lang.String[] { "Num", "Name", });
    internal_static_SimpleList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SimpleList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SimpleList_descriptor,
        new java.lang.String[] { "SimpleList", });
    internal_static_SimpleFeature_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_SimpleFeature_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SimpleFeature_descriptor,
        new java.lang.String[] { "Name", "Location", });
    internal_static_SimpleSummary_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_SimpleSummary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SimpleSummary_descriptor,
        new java.lang.String[] { "FeatureCount", });
    internal_static_SimpleFeatureDatabase_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_SimpleFeatureDatabase_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SimpleFeatureDatabase_descriptor,
        new java.lang.String[] { "Feature", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
