// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: json.prop

package com.finace.miscroservice.rpc.com.test;

public interface SimpleSummaryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SimpleSummary)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 feature_count = 2;</code>
   */
  int getFeatureCount();
}
