// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: json.prop

package com.finace.miscroservice.rpc.com.test;

public interface SimpleFeatureOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SimpleFeature)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.Simple location = 2;</code>
   */
  boolean hasLocation();
  /**
   * <code>.Simple location = 2;</code>
   */
  com.finace.miscroservice.rpc.com.test.Simple getLocation();
  /**
   * <code>.Simple location = 2;</code>
   */
  com.finace.miscroservice.rpc.com.test.SimpleOrBuilder getLocationOrBuilder();
}
