// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: json.prop

package com.finace.miscroservice.rpc.com.test;

public interface SimpleListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SimpleList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Simple simpleList = 1;</code>
   */
  java.util.List<com.finace.miscroservice.rpc.com.test.Simple> 
      getSimpleListList();
  /**
   * <code>repeated .Simple simpleList = 1;</code>
   */
  com.finace.miscroservice.rpc.com.test.Simple getSimpleList(int index);
  /**
   * <code>repeated .Simple simpleList = 1;</code>
   */
  int getSimpleListCount();
  /**
   * <code>repeated .Simple simpleList = 1;</code>
   */
  java.util.List<? extends com.finace.miscroservice.rpc.com.test.SimpleOrBuilder> 
      getSimpleListOrBuilderList();
  /**
   * <code>repeated .Simple simpleList = 1;</code>
   */
  com.finace.miscroservice.rpc.com.test.SimpleOrBuilder getSimpleListOrBuilder(
      int index);
}
